#!/bin/bash
sudo apt update
sudo apt install openjdk-11-jdk -y
sudo apt install maven -y
curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee \
  /usr/share/keyrings/jenkins-keyring.asc > /dev/null
  
echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
  https://pkg.jenkins.io/debian-stable binary/ | sudo tee \
  /etc/apt/sources.list.d/jenkins.list > /dev/null

sudo apt-get update
sudo apt-get install jenkins -y


#### Explanation generated by ChatGPT because im lazy####
#1. Update package lists:
#   - `sudo apt update`: Updates the package lists of available packages.

#2. Install OpenJDK and Maven:
#   - `sudo apt install openjdk-11-jdk -y`: Installs OpenJDK 11 package.
#   - `sudo apt install maven -y`: Installs Maven.

#3. Configure Jenkins repository:
#   - `curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | sudo tee /usr/share/keyrings/jenkins-keyring.asc > /dev/null`: Downloads and saves the Jenkins repository key as `jenkins-keyring.asc` in `/usr/share/keyrings/` directory.
#   - `echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list > /dev/null`: Adds the Jenkins repository to the system's package sources by appending the repository URL to `/etc/apt/sources.list.d/jenkins.list` file.

#4. Update package lists and install Jenkins:
#   - `sudo apt-get update`: Updates the package lists of available packages to include the newly added Jenkins repository.
#   - `sudo apt-get install jenkins -y`: Installs Jenkins.

#Please note that the script includes commented lines (lines starting with `#`) which are not executed and might be provided for reference or optional commands.
