#!/bin/bash
yum install java-1.8.0-openjdk.x86_64 wget -y   
mkdir -p /opt/nexus/   
mkdir -p /tmp/nexus/                           
cd /tmp/nexus/
NEXUSURL="https://download.sonatype.com/nexus/3/latest-unix.tar.gz"
wget $NEXUSURL -O nexus.tar.gz
EXTOUT=`tar xzvf nexus.tar.gz`
NEXUSDIR=`echo $EXTOUT | cut -d '/' -f1`
rm -rf /tmp/nexus/nexus.tar.gz
rsync -avzh /tmp/nexus/ /opt/nexus/
useradd nexus
chown -R nexus.nexus /opt/nexus 
cat <<EOT>> /etc/systemd/system/nexus.service
[Unit]                                                                          
Description=nexus service                                                       
After=network.target                                                            
                                                                  
[Service]                                                                       
Type=forking                                                                    
LimitNOFILE=65536                                                               
ExecStart=/opt/nexus/$NEXUSDIR/bin/nexus start                                  
ExecStop=/opt/nexus/$NEXUSDIR/bin/nexus stop                                    
User=nexus                                                                      
Restart=on-abort                                                                
                                                                  
[Install]                                                                       
WantedBy=multi-user.target                                                      

EOT

echo 'run_as_user="nexus"' > /opt/nexus/$NEXUSDIR/bin/nexus.rc
systemctl daemon-reload
systemctl start nexus
systemctl enable nexus


#### Explanation generated by ChatGPT because im lazy####
#1. Install Java and prepare directories:
#   - `yum install java-1.8.0-openjdk.x86_64 wget -y`: Installs Java 8 and wget using the yum package manager.
#   - `mkdir -p /opt/nexus/` and `mkdir -p /tmp/nexus/`: Creates the `/opt/nexus/` and `/tmp/nexus/` directories if they don't exist.

#2. Download and extract Nexus:
#   - `cd /tmp/nexus/`: Changes the working directory to `/tmp/nexus/`.
#   - `NEXUSURL="https://download.sonatype.com/nexus/3/latest-unix.tar.gz"`: Sets the Nexus download URL.
#   - `wget $NEXUSURL -O nexus.tar.gz`: Downloads the Nexus tarball from the specified URL and saves it as `nexus.tar.gz`.
#   - `EXTOUT=`tar xzvf nexus.tar.gz``: Extracts the contents of the `nexus.tar.gz` file and assigns the output to the `EXTOUT` variable.
#   - `NEXUSDIR=`echo $EXTOUT | cut -d '/' -f1``: Extracts the directory name from the extracted output and assigns it to the `NEXUSDIR` variable.
#   - `rm -rf /tmp/nexus/nexus.tar.gz`: Removes the downloaded Nexus tarball.
#   - `rsync -avzh /tmp/nexus/ /opt/nexus/`: Copies the extracted Nexus files from `/tmp/nexus/` to `/opt/nexus/`.

#3. Configure Nexus service:
#   - `useradd nexus`: Creates a new user named `nexus`.
#   - `chown -R nexus.nexus /opt/nexus`: Changes the ownership of the `/opt/nexus/` directory and its contents to the `nexus` user.
#   - `cat <<EOT>> /etc/systemd/system/nexus.service`: Appends a systemd service unit file for Nexus with the specified content.
#   - `echo 'run_as_user="nexus"' > /opt/nexus/$NEXUSDIR/bin/nexus.rc`: Creates a configuration file for Nexus specifying the `nexus` user.

#4. Start and enable Nexus service:
#   - `systemctl daemon-reload`: Reloads the systemd daemon to apply any changes made to service unit files.
#   - `systemctl start nexus`: Starts the Nexus service.
#   - `systemctl enable nexus`: Enables the Nexus service to start on system boot.

#Please note that this script assumes a CentOS or RHEL-based system (using `yum` package manager) and installs Nexus version 3.