#!/bin/bash
cp /etc/sysctl.conf /root/sysctl.conf_backup
cat <<EOT> /etc/sysctl.conf
vm.max_map_count=262144
fs.file-max=65536
ulimit -n 65536
ulimit -u 4096
EOT
cp /etc/security/limits.conf /root/sec_limit.conf_backup
cat <<EOT> /etc/security/limits.conf
sonarqube   -   nofile   65536
sonarqube   -   nproc    409
EOT

sudo apt-get update -y
sudo apt-get install openjdk-11-jdk -y
sudo update-alternatives --config java

java -version

sudo apt update
wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -

sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
sudo apt install postgresql postgresql-contrib -y
#sudo -u postgres psql -c "SELECT version();"
sudo systemctl enable postgresql.service
sudo systemctl start  postgresql.service
sudo echo "postgres:admin123" | chpasswd
runuser -l postgres -c "createuser sonar"
sudo -i -u postgres psql -c "ALTER USER sonar WITH ENCRYPTED PASSWORD 'admin123';"
sudo -i -u postgres psql -c "CREATE DATABASE sonarqube OWNER sonar;"
sudo -i -u postgres psql -c "GRANT ALL PRIVILEGES ON DATABASE sonarqube to sonar;"
systemctl restart  postgresql
#systemctl status -l   postgresql
netstat -tulpena | grep postgres
sudo mkdir -p /sonarqube/
cd /sonarqube/
sudo curl -O https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-8.3.0.34182.zip
sudo apt-get install zip -y
sudo unzip -o sonarqube-8.3.0.34182.zip -d /opt/
sudo mv /opt/sonarqube-8.3.0.34182/ /opt/sonarqube
sudo groupadd sonar
sudo useradd -c "SonarQube - User" -d /opt/sonarqube/ -g sonar sonar
sudo chown sonar:sonar /opt/sonarqube/ -R
cp /opt/sonarqube/conf/sonar.properties /root/sonar.properties_backup
cat <<EOT> /opt/sonarqube/conf/sonar.properties
sonar.jdbc.username=sonar
sonar.jdbc.password=admin123
sonar.jdbc.url=jdbc:postgresql://localhost/sonarqube
sonar.web.host=0.0.0.0
sonar.web.port=9000
sonar.web.javaAdditionalOpts=-server
sonar.search.javaOpts=-Xmx512m -Xms512m -XX:+HeapDumpOnOutOfMemoryError
sonar.log.level=INFO
sonar.path.logs=logs
EOT

cat <<EOT> /etc/systemd/system/sonarqube.service
[Unit]
Description=SonarQube service
After=syslog.target network.target

[Service]
Type=forking

ExecStart=/opt/sonarqube/bin/linux-x86-64/sonar.sh start
ExecStop=/opt/sonarqube/bin/linux-x86-64/sonar.sh stop

User=sonar
Group=sonar
Restart=always

LimitNOFILE=65536
LimitNPROC=4096


[Install]
WantedBy=multi-user.target
EOT

systemctl daemon-reload
systemctl enable sonarqube.service
#systemctl start sonarqube.service
#systemctl status -l sonarqube.service
apt-get install nginx -y
rm -rf /etc/nginx/sites-enabled/default
rm -rf /etc/nginx/sites-available/default
cat <<EOT> /etc/nginx/sites-available/sonarqube
server{
    listen      80;
    server_name sonarqube.groophy.in;

    access_log  /var/log/nginx/sonar.access.log;
    error_log   /var/log/nginx/sonar.error.log;

    proxy_buffers 16 64k;
    proxy_buffer_size 128k;

    location / {
        proxy_pass  http://127.0.0.1:9000;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
              
        proxy_set_header    Host            \$host;
        proxy_set_header    X-Real-IP       \$remote_addr;
        proxy_set_header    X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header    X-Forwarded-Proto http;
    }
}
EOT
ln -s /etc/nginx/sites-available/sonarqube /etc/nginx/sites-enabled/sonarqube
systemctl enable nginx.service
#systemctl restart nginx.service
sudo ufw allow 80,9000,9001/tcp

echo "System reboot in 30 sec"
sleep 30
reboot


####Explanation generated by ChatGPT ####



#1. Copy sysctl.conf and limits.conf files:
#   - `cp /etc/sysctl.conf /root/sysctl.conf_backup`: Creates a backup of the `sysctl.conf` file.
#   - `cat <<EOT> /etc/sysctl.conf`: Opens the `sysctl.conf` file for editing.
#   - Within the here-document block (`<<EOT` to `EOT`), the script modifies the `sysctl.conf` file by setting specific configuration values such as `vm.max_map_count` and `fs.file-max`.
#   - `cp /etc/security/limits.conf /root/sec_limit.conf_backup`: Creates a backup of the `limits.conf` file.
#   - `cat <<EOT> /etc/security/limits.conf`: Opens the `limits.conf` file for editing.
#   - Within the document block, the script modifies the `limits.conf` file by setting resource limits for the `sonarqube` user.

#2. Update and install dependencies:
#   - `sudo apt-get update -y`: Updates the package lists of available packages.
#   - `sudo apt-get install openjdk-11-jdk -y`: Installs the OpenJDK 11 package.
#   - `sudo update-alternatives --config java`: Configures the default Java version.
#   - `java -version`: Displays the installed Java version.
#   - `sudo apt update`: Updates the package lists of available packages.
#   - `wget -q https://www.postgresql.org/media/keys/ACCC4CF8.asc -O - | sudo apt-key add -`: Retrieves the PostgreSQL repository key and adds it to the system.
#  - `sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'`: Adds the PostgreSQL repository to the system's package sources.
#   - `sudo apt install postgresql postgresql-contrib -y`: Installs PostgreSQL and its additional modules.

#3. Configure PostgreSQL:
#   - Several commands starting with `sudo -i -u postgres psql -c` create a PostgreSQL user, configure its password, create a database, and grant privileges on that database.

#4. Set up SonarQube:
#   - The script downloads the SonarQube distribution, extracts it to `/opt/sonarqube`, creates a dedicated user and group for SonarQube, and sets the necessary permissions.
#   - It backs up the default `sonar.properties` file and replaces it with a modified version.
#   - It creates a systemd service unit file for SonarQube.

#5. Configure NGINX:
#   - The script installs NGINX and creates an NGINX server block configuration file for SonarQube.
#   - It enables the SonarQube server block by creating a symbolic link in the appropriate directory.

#6. Enable firewall rules:
#   - `sudo ufw allow 80,9000,9001/tcp`: Opens the specified ports in the firewall.

#7. Reboot the system:
#   - `echo "System reboot in 30 sec"`: Prints a message indicating a system reboot.
#   - `sleep 30`: Pauses the script execution for 30 seconds.
#   - `reboot`: Initiates a system reboot.

#Please note that some parts of the script are commented out (lines starting with `#`) or have commented-out commands. These lines are not executed and are provided as reference or optional commands.
